name: lottie_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  awesome_snackbar_content: ^0.1.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  lottie: ^3.1.2
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
